[package]
name = "narrow-derive"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
once_cell = "1"
proc-macro-crate = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", default-features = false, features = [
  "derive",
  "extra-traits",
  "visit",
  "visit-mut",
] }

[dev-dependencies]
macrotest = "1"
