[package]
name = "narrow-derive"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[features]

[dependencies]
proc-macro-crate = "1"
proc-macro2 = "1"
quote = "1"
syn = "1"
