status = [
    "Check (nightly)",
    "Test (nightly)",
    "Rustfmt (nightly)",
    "Clippy (nightly)",
    "Miri (nightly)",
    "Rustdoc (nightly)"
]
delete_merged_branches = true
timeout_sec = 600
