status = [
    "Check (stable)",
    "Test (stable)",
    "Rustfmt",
    "Clippy (stable)",
    "Miri",
    "Rustdoc (stable)",
    "Bench (stable)",
]
delete_merged_branches = true
timeout_sec = 600
