[workspace.package]
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2021"
rust-version = "1.70.0"
description = "An implementation of Apache Arrow"
readme = "README.md"
repository = "https://github.com/mbrobbel/narrow"
documentation = "http://docs.rs/narrow/"
license = "Apache-2.0 OR MIT"
keywords = ["Arrow"]
categories = ["data-structures"]

[workspace]
members = ["narrow-derive"]

[package]
name = "narrow"
version= "0.3.4"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["arrow-rs", "derive"]
arrow-rs = ["dep:arrow-array", "dep:arrow-buffer", "dep:arrow-schema", "narrow-derive?/arrow-rs"]
derive = ["dep:narrow-derive"]

[dependencies]
# arrow-array = { version = "49.0.0", optional = true }
# arrow-buffer = { version = "49.0.0", optional = true }
# arrow-schema = { version = "49.0.0", optional = true }
arrow-array = { git = "https://github.com/mbrobbel/arrow-rs", branch = "buffer-builder-scalar-buffer", optional = true }
# arrow-buffer = { git = "https://github.com/apache/arrow-rs", branch = "master", optional = true }
arrow-buffer = { git = "https://github.com/mbrobbel/arrow-rs", branch = "buffer-builder-scalar-buffer", optional = true }
arrow-schema = { git = "https://github.com/mbrobbel/arrow-rs", branch = "buffer-builder-scalar-buffer", optional = true }
narrow-derive = { path = "narrow-derive", version = "^0.3.4", optional = true }

[dev-dependencies]
# arrow-cast = { version = "49.0.0", default-features = false, features = ["prettyprint"] }
arrow-cast = { git = "https://github.com/mbrobbel/arrow-rs", branch = "buffer-builder-scalar-buffer", default-features = false, features = ["prettyprint"] }
bytes = "1.5.0"
criterion = { version = "0.5.1", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
parquet = { git = "https://github.com/mbrobbel/arrow-rs", branch = "buffer-builder-scalar-buffer", features = ["arrow"] }
# parquet = { version = "49.0.0", default-features = false, features = ["arrow"] }

[profile.bench]
lto = true
codegen-units = 1

[[bench]]
name = "narrow"
harness = false

[[example]]
name = "parquet"
required-features = ["arrow-rs", "derive"]
