[package]
name = "narrow"
version = "0.2.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2021"
# rust-version = "nightly"
description = "An implementation of Apache Arrow"
readme = "README.md"
repository = "https://github.com/mbrobbel/narrow"
documentation = "http://docs.rs/narrow/"
license = "Apache-2.0 OR MIT"
keywords = ["Arrow"]
categories = ["data-structures"]

[features]
default = ["nightly"]
nightly = ["extend_one", "portable_simd", "trusted_len"]
extend_one = []
portable_simd = []
trusted_len = []

[dependencies]
# narrow-derive = { version = "0.2.0", path = "narrow-derive" }

[dev-dependencies]
criterion = "0.3"
rand = "0.8"

[profile.bench]
lto = true
codegen-units = 1

[[bench]]
name = "narrow"
harness = false

[workspace]
members = [
  "narrow-derive"
]
