[workspace]
members = [
  "narrow-derive"
]

[package]
name = "narrow"
version = "0.1.0"
authors = ["Matthijs Brobbel <m1brobbel@gmail.com>"]
edition = "2018"
description = "A Rust implementation of Apache Arrow"
readme = "README.md"
repository = "https://github.com/mbrobbel/narrow"
license = "Apache-2.0 or MIT"
keywords = ["Arrow"]
categories = ["data-structures"]

[features]
default = []

[dependencies]
bitvec = { version= "0.22", default-features = false }
narrow-derive = { version = "0.1.0", path = "narrow-derive" }

[dev-dependencies]
criterion = "0.3"

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1

[[bench]]
name = "narrow"
harness = false
