#format_code_in_doc_comments = true
#format_strings = true
#group_imports = "StdExternalCrate"
#hex_literal_case = "Lower"
#imports_granularity = "Crate"
#normalize_comments = true
#reorder_impl_items = true
use_field_init_shorthand = true
#wrap_comments = true
