name: Bench

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    name: Bench
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo bench --bench narrow -- --output-format=bencher | tee output.txt
      - uses: benchmark-action/github-action-benchmark@v1
        with:
          name: narrow
          tool: cargo
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          comment-on-alert: true
          alert-comment-cc-users: "@mbrobbel"
