name: Bench

on:
  push:
    branches:
      - main
      - trying
      - staging
  pull_request:

jobs:
  run:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo bench --bench narrow -- --output-format=bencher | tee output.txt
      - uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: output.txt

  deploy:
    name: Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [run]
    environment:
      name: benchmark-results
      url: https://mbrobbel.github.io/narrow-benchmark-results/
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: benchmark-results
      - uses: benchmark-action/github-action-benchmark@v1
        with:
          name: narrow
          tool: cargo
          output-file-path: output.txt
          gh-pages-branch: main
          gh-repository: github.com/mbrobbel/narrow-benchmark-results
          benchmark-data-dir-path: .
          github-token: ${{ secrets.BENCHMARK_RESULTS }}
          auto-push: true
          comment-on-alert: true
          alert-comment-cc-users: "@mbrobbel"
