name: Docs

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --no-deps
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: rustdoc
          path: target/doc

  deploy:
    name: Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [rustdoc]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/narrow
    concurrency:
      group: github-pages
      cancel-in-progress: true
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: rustdoc
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - uses: actions/deploy-pages@v1
        id: deployment
