name: Docs

on: [push, pull_request]

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
      - uses: actions/upload-artifact@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          path: target/doc

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [rustdoc]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/download-artifact@v2
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
