name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    concurrency: release
    outputs:
      skip: ${{ steps.changelog.outputs.skip }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-
            ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-smart-release@0.20.0 --locked || true
      - run: cargo check --all
      - id: changelog
        run: cargo changelog --no-preview narrow narrow-derive || echo "skip=true" >> "$GITHUB_OUTPUT"

  release:
    name: Release
    needs: changelog
    runs-on: ubuntu-latest
    concurrency: release
    if: needs.changelog.outputs.skip != 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-
            ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-smart-release@0.20.0 --locked || true
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo smart-release \
            --update-crates-index \
            --allow-fully-generated-changelogs \
            --no-changelog-preview \
            --verbose \
            --execute \
            narrow
