name: Release

on:
  push:
    tags:
    - '**'

jobs:
  github:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: softprops/action-gh-release@v0.1.7

  crates:
    name: Crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: publish
        args: --token ${{ secrets.CRATES_IO_TOKEN }} --manifest-path narrow-derive/Cargo.toml
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: publish
        args: --token ${{ secrets.CRATES_IO_TOKEN }}
